# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageProcessing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ImageProcessing.proto\"S\n\x11PredictionRequest\x12\x13\n\x0bimage_array\x18\x01 \x01(\x0c\x12\x16\n\x0e\x66ile_extension\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\"*\n\x10PredictionResult\x12\x16\n\x0e\x64\x65tected_image\x18\x01 \x01(\t2C\n\x0fImageProcessing\x12\x30\n\x07Predict\x12\x12.PredictionRequest\x1a\x11.PredictionResultb\x06proto3')



_PREDICTIONREQUEST = DESCRIPTOR.message_types_by_name['PredictionRequest']
_PREDICTIONRESULT = DESCRIPTOR.message_types_by_name['PredictionResult']
PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONREQUEST,
  '__module__' : 'ImageProcessing_pb2'
  # @@protoc_insertion_point(class_scope:PredictionRequest)
  })
_sym_db.RegisterMessage(PredictionRequest)

PredictionResult = _reflection.GeneratedProtocolMessageType('PredictionResult', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONRESULT,
  '__module__' : 'ImageProcessing_pb2'
  # @@protoc_insertion_point(class_scope:PredictionResult)
  })
_sym_db.RegisterMessage(PredictionResult)

_IMAGEPROCESSING = DESCRIPTOR.services_by_name['ImageProcessing']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTIONREQUEST._serialized_start=25
  _PREDICTIONREQUEST._serialized_end=108
  _PREDICTIONRESULT._serialized_start=110
  _PREDICTIONRESULT._serialized_end=152
  _IMAGEPROCESSING._serialized_start=154
  _IMAGEPROCESSING._serialized_end=221
# @@protoc_insertion_point(module_scope)
